# coding: utf-8

"""
    Polaris API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from polarisgenclient.api_client import ApiClient


class IpFilterRuleApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def ip_filter_rule_delete(self, ip_filter_id, id, seq, **kwargs):  # noqa: E501
        """IpFilterRuleRoute.delete  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ip_filter_rule_delete(ip_filter_id, id, seq, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str ip_filter_id: IpFilter id name (required)
        :param str id: UUID1 string (required)
        :param int seq: seq (required)
        :return: IpFilterRuleObject
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ip_filter_rule_delete_with_http_info(ip_filter_id, id, seq, **kwargs)  # noqa: E501
        else:
            (data) = self.ip_filter_rule_delete_with_http_info(ip_filter_id, id, seq, **kwargs)  # noqa: E501
            return data

    def ip_filter_rule_delete_with_http_info(self, ip_filter_id, id, seq, **kwargs):  # noqa: E501
        """IpFilterRuleRoute.delete  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ip_filter_rule_delete_with_http_info(ip_filter_id, id, seq, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str ip_filter_id: IpFilter id name (required)
        :param str id: UUID1 string (required)
        :param int seq: seq (required)
        :return: IpFilterRuleObject
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['ip_filter_id', 'id', 'seq']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ip_filter_rule_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'ip_filter_id' is set
        if ('ip_filter_id' not in params or
                params['ip_filter_id'] is None):
            raise ValueError("Missing the required parameter `ip_filter_id` when calling `ip_filter_rule_delete`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `ip_filter_rule_delete`")  # noqa: E501
        # verify the required parameter 'seq' is set
        if ('seq' not in params or
                params['seq'] is None):
            raise ValueError("Missing the required parameter `seq` when calling `ip_filter_rule_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'ip_filter_id' in params:
            path_params['ip_filter_id'] = params['ip_filter_id']  # noqa: E501
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501
        if 'seq' in params:
            path_params['seq'] = params['seq']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/api/v0.1/ipfilter/{ip_filter_id}/rule/{id}/seq/{seq}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='IpFilterRuleObject',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def ip_filter_rule_get(self, **kwargs):  # noqa: E501
        """IpFilterRuleRoute.get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ip_filter_rule_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: IpFilterRuleObject
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ip_filter_rule_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.ip_filter_rule_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def ip_filter_rule_get_with_http_info(self, **kwargs):  # noqa: E501
        """IpFilterRuleRoute.get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ip_filter_rule_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: IpFilterRuleObject
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ip_filter_rule_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['ApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/api/v0.1/ipfilter/rule', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='IpFilterRuleObject',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def ip_filter_rule_get_by_id(self, ip_filter_id, **kwargs):  # noqa: E501
        """IpFilterRuleRoute.get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ip_filter_rule_get_by_id(ip_filter_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str ip_filter_id: IpFilter id (required)
        :return: IpFilterRuleObject
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ip_filter_rule_get_by_id_with_http_info(ip_filter_id, **kwargs)  # noqa: E501
        else:
            (data) = self.ip_filter_rule_get_by_id_with_http_info(ip_filter_id, **kwargs)  # noqa: E501
            return data

    def ip_filter_rule_get_by_id_with_http_info(self, ip_filter_id, **kwargs):  # noqa: E501
        """IpFilterRuleRoute.get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ip_filter_rule_get_by_id_with_http_info(ip_filter_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str ip_filter_id: IpFilter id (required)
        :return: IpFilterRuleObject
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['ip_filter_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ip_filter_rule_get_by_id" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'ip_filter_id' is set
        if ('ip_filter_id' not in params or
                params['ip_filter_id'] is None):
            raise ValueError("Missing the required parameter `ip_filter_id` when calling `ip_filter_rule_get_by_id`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'ip_filter_id' in params:
            path_params['ip_filter_id'] = params['ip_filter_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['ApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/api/v0.1/ipfilter/{ip_filter_id}/rule', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='IpFilterRuleObject',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def ip_filter_rule_post(self, **kwargs):  # noqa: E501
        """IpFilterRuleRoute.post  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ip_filter_rule_post(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param IpFilterRuleObject body: IpFilterRule object
        :return: IpFilterRuleObject
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ip_filter_rule_post_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.ip_filter_rule_post_with_http_info(**kwargs)  # noqa: E501
            return data

    def ip_filter_rule_post_with_http_info(self, **kwargs):  # noqa: E501
        """IpFilterRuleRoute.post  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ip_filter_rule_post_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param IpFilterRuleObject body: IpFilterRule object
        :return: IpFilterRuleObject
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ip_filter_rule_post" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/api/v0.1/ipfilter/rule', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='IpFilterRuleObject',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def ip_filter_rule_put(self, ip_filter_id, id, seq, **kwargs):  # noqa: E501
        """IpFilterRuleRoute.put  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ip_filter_rule_put(ip_filter_id, id, seq, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str ip_filter_id: IpFilterRule id (required)
        :param str id: UUID1 string (required)
        :param int seq: seq (required)
        :param IpFilterRuleObject body: IpFilterRule object
        :return: IpFilterRuleObject
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ip_filter_rule_put_with_http_info(ip_filter_id, id, seq, **kwargs)  # noqa: E501
        else:
            (data) = self.ip_filter_rule_put_with_http_info(ip_filter_id, id, seq, **kwargs)  # noqa: E501
            return data

    def ip_filter_rule_put_with_http_info(self, ip_filter_id, id, seq, **kwargs):  # noqa: E501
        """IpFilterRuleRoute.put  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ip_filter_rule_put_with_http_info(ip_filter_id, id, seq, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str ip_filter_id: IpFilterRule id (required)
        :param str id: UUID1 string (required)
        :param int seq: seq (required)
        :param IpFilterRuleObject body: IpFilterRule object
        :return: IpFilterRuleObject
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['ip_filter_id', 'id', 'seq', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ip_filter_rule_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'ip_filter_id' is set
        if ('ip_filter_id' not in params or
                params['ip_filter_id'] is None):
            raise ValueError("Missing the required parameter `ip_filter_id` when calling `ip_filter_rule_put`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `ip_filter_rule_put`")  # noqa: E501
        # verify the required parameter 'seq' is set
        if ('seq' not in params or
                params['seq'] is None):
            raise ValueError("Missing the required parameter `seq` when calling `ip_filter_rule_put`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'ip_filter_id' in params:
            path_params['ip_filter_id'] = params['ip_filter_id']  # noqa: E501
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501
        if 'seq' in params:
            path_params['seq'] = params['seq']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/api/v0.1/ipfilter/{ip_filter_id}/rule/{id}/seq/{seq}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='IpFilterRuleObject',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
