# coding: utf-8

"""
    Polaris API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DeviceInterfaceAddressObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'device_name': 'str',
        'ip_address': 'str',
        'netmask': 'str',
        'port': 'str',
        'prefixlen': 'int'
    }

    attribute_map = {
        'device_name': 'device_name',
        'ip_address': 'ip_address',
        'netmask': 'netmask',
        'port': 'port',
        'prefixlen': 'prefixlen'
    }

    def __init__(self, device_name=None, ip_address=None, netmask=None, port=None, prefixlen=None):  # noqa: E501
        """DeviceInterfaceAddressObject - a model defined in Swagger"""  # noqa: E501

        self._device_name = None
        self._ip_address = None
        self._netmask = None
        self._port = None
        self._prefixlen = None
        self.discriminator = None

        if device_name is not None:
            self.device_name = device_name
        if ip_address is not None:
            self.ip_address = ip_address
        if netmask is not None:
            self.netmask = netmask
        if port is not None:
            self.port = port
        if prefixlen is not None:
            self.prefixlen = prefixlen

    @property
    def device_name(self):
        """Gets the device_name of this DeviceInterfaceAddressObject.  # noqa: E501


        :return: The device_name of this DeviceInterfaceAddressObject.  # noqa: E501
        :rtype: str
        """
        return self._device_name

    @device_name.setter
    def device_name(self, device_name):
        """Sets the device_name of this DeviceInterfaceAddressObject.


        :param device_name: The device_name of this DeviceInterfaceAddressObject.  # noqa: E501
        :type: str
        """

        self._device_name = device_name

    @property
    def ip_address(self):
        """Gets the ip_address of this DeviceInterfaceAddressObject.  # noqa: E501


        :return: The ip_address of this DeviceInterfaceAddressObject.  # noqa: E501
        :rtype: str
        """
        return self._ip_address

    @ip_address.setter
    def ip_address(self, ip_address):
        """Sets the ip_address of this DeviceInterfaceAddressObject.


        :param ip_address: The ip_address of this DeviceInterfaceAddressObject.  # noqa: E501
        :type: str
        """

        self._ip_address = ip_address

    @property
    def netmask(self):
        """Gets the netmask of this DeviceInterfaceAddressObject.  # noqa: E501


        :return: The netmask of this DeviceInterfaceAddressObject.  # noqa: E501
        :rtype: str
        """
        return self._netmask

    @netmask.setter
    def netmask(self, netmask):
        """Sets the netmask of this DeviceInterfaceAddressObject.


        :param netmask: The netmask of this DeviceInterfaceAddressObject.  # noqa: E501
        :type: str
        """

        self._netmask = netmask

    @property
    def port(self):
        """Gets the port of this DeviceInterfaceAddressObject.  # noqa: E501


        :return: The port of this DeviceInterfaceAddressObject.  # noqa: E501
        :rtype: str
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this DeviceInterfaceAddressObject.


        :param port: The port of this DeviceInterfaceAddressObject.  # noqa: E501
        :type: str
        """

        self._port = port

    @property
    def prefixlen(self):
        """Gets the prefixlen of this DeviceInterfaceAddressObject.  # noqa: E501


        :return: The prefixlen of this DeviceInterfaceAddressObject.  # noqa: E501
        :rtype: int
        """
        return self._prefixlen

    @prefixlen.setter
    def prefixlen(self, prefixlen):
        """Sets the prefixlen of this DeviceInterfaceAddressObject.


        :param prefixlen: The prefixlen of this DeviceInterfaceAddressObject.  # noqa: E501
        :type: int
        """

        self._prefixlen = prefixlen

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DeviceInterfaceAddressObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeviceInterfaceAddressObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
