# coding: utf-8

"""
    Polaris API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SystemImageBootObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cmdline': 'str',
        'initrd': 'list[object]',
        'kernel': 'str'
    }

    attribute_map = {
        'cmdline': 'cmdline',
        'initrd': 'initrd',
        'kernel': 'kernel'
    }

    def __init__(self, cmdline=None, initrd=None, kernel=None):  # noqa: E501
        """SystemImageBootObject - a model defined in Swagger"""  # noqa: E501

        self._cmdline = None
        self._initrd = None
        self._kernel = None
        self.discriminator = None

        if cmdline is not None:
            self.cmdline = cmdline
        if initrd is not None:
            self.initrd = initrd
        self.kernel = kernel

    @property
    def cmdline(self):
        """Gets the cmdline of this SystemImageBootObject.  # noqa: E501


        :return: The cmdline of this SystemImageBootObject.  # noqa: E501
        :rtype: str
        """
        return self._cmdline

    @cmdline.setter
    def cmdline(self, cmdline):
        """Sets the cmdline of this SystemImageBootObject.


        :param cmdline: The cmdline of this SystemImageBootObject.  # noqa: E501
        :type: str
        """

        self._cmdline = cmdline

    @property
    def initrd(self):
        """Gets the initrd of this SystemImageBootObject.  # noqa: E501


        :return: The initrd of this SystemImageBootObject.  # noqa: E501
        :rtype: list[object]
        """
        return self._initrd

    @initrd.setter
    def initrd(self, initrd):
        """Sets the initrd of this SystemImageBootObject.


        :param initrd: The initrd of this SystemImageBootObject.  # noqa: E501
        :type: list[object]
        """

        self._initrd = initrd

    @property
    def kernel(self):
        """Gets the kernel of this SystemImageBootObject.  # noqa: E501


        :return: The kernel of this SystemImageBootObject.  # noqa: E501
        :rtype: str
        """
        return self._kernel

    @kernel.setter
    def kernel(self, kernel):
        """Sets the kernel of this SystemImageBootObject.


        :param kernel: The kernel of this SystemImageBootObject.  # noqa: E501
        :type: str
        """
        if kernel is None:
            raise ValueError("Invalid value for `kernel`, must not be `None`")  # noqa: E501

        self._kernel = kernel

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SystemImageBootObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SystemImageBootObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
